import { useEffect, useMemo, useState } from 'react';
import { Bell, Check, ChevronRight, Image, Lock, Palette, Save, Search, Server, Shield, SlidersHorizontal, User, Users, Volume2, X, Zap } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? 'http://localhost:5000' : 'https://backend-tavora.fly.dev');
const navGroups = [
  { title: 'Compte', icon: User, items: [['account', 'Infos du compte'], ['security', 'Mot de passe et sécurité'], ['voice', 'Voix & Vidéo']] },
  { title: 'Profil', icon: Image, items: [['profile', 'Profil'], ['status', 'Statut personnalisé']] },
  { title: 'Confidentialité', icon: Lock, items: [['privacy', 'Confidentialité et sécurité'], ['friends', 'Amis et demandes']] },
  { title: 'Notifications', icon: Bell, items: [['notifications', 'Notifications générales']] },
  { title: 'Apparence', icon: Palette, items: [['appearance', 'Thème et interface']] },
  { title: 'Messages', icon: Users, items: [['messages', 'Préférences de messagerie']] },
  { title: 'Accessibilité', icon: SlidersHorizontal, items: [['accessibility', 'Accessibilité visuelle']] },
  { title: 'Communautés', icon: Server, items: [['servers', 'Mes serveurs']] },
  { title: 'Zone dangereuse', icon: Shield, items: [['danger', 'Actions du compte']] },
];
const fieldClass = 'mt-2 w-full rounded-lg border border-white/[0.08] bg-[#101017] px-3 py-2.5 text-sm text-white outline-none transition placeholder:text-white/25 focus:border-cyan-200/40 focus:ring-2 focus:ring-cyan-200/10';

export default function AccountSettingsModal({ isOpen, user, servers = [], friends = [], incomingRequests = [], outgoingRequests = [], onClose, onOpenProfile, onOpenServerSettings, onChangePassword, onUpdateUser, onSaveProfile, onLeaveServer, onLogout, getAuthHeaders, initialTab = 'account', onActiveChange }) {
  const [active, setActive] = useState('account');
  const [mobileView, setMobileView] = useState('navigation');
  const [isMobile, setIsMobile] = useState(() => window.matchMedia?.('(max-width: 640px)').matches ?? false);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  const [profile, setProfile] = useState({ displayName: '', username: '', bio: '' });
  const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [privacy, setPrivacy] = useState({ friendRequests: 'everyone', directMessages: 'everyone', activity: { enabled: false, games: true, applications: true, showName: true, showDuration: true, ignoredApplications: [] } });
  const [notifications, setNotifications] = useState({ enabled: true, desktop: true, preview: true, avatar: true, duration: 5, messages: true, mentions: true, friendRequests: true, directMessages: true, servers: true });
  const [accessibility, setAccessibility] = useState({ textSize: 'normal', reduceMotion: false, highContrast: false });
  const [voiceVideo, setVoiceVideo] = useState({ inputDeviceId: '', inputVolume: 100, noiseSuppression: true, echoCancellation: true, autoGainControl: true, cameraEnabled: false });
  const [devices, setDevices] = useState([]);

  useEffect(() => {
    if (!isOpen) return;
    setActive(initialTab);
    setProfile({ displayName: user?.displayName || '', username: user?.username || '', bio: user?.bio || '' });
    setPrivacy({ friendRequests: 'everyone', directMessages: 'everyone', activity: { enabled: false, games: true, applications: true, showName: true, showDuration: true, ignoredApplications: [], ...(user?.privacy?.activity || {}) }, ...(user?.privacy || {}) });
    setNotifications({ enabled: true, desktop: true, preview: true, avatar: true, duration: 5, messages: true, mentions: true, friendRequests: true, directMessages: true, servers: true, ...(user?.notifications || {}) });
    setAccessibility({ textSize: 'normal', reduceMotion: false, highContrast: false, ...(user?.accessibility || {}) });
    setVoiceVideo({ inputDeviceId: '', inputVolume: 100, noiseSuppression: true, echoCancellation: true, autoGainControl: true, cameraEnabled: false, ...(user?.voiceVideo || {}) });
    setStatus(user?.customStatus || '');
  }, [initialTab, isOpen, user]);

  useEffect(() => {
    const media = window.matchMedia('(max-width: 640px)');
    const update = () => setIsMobile(media.matches);
    update();
    media.addEventListener?.('change', update);
    return () => media.removeEventListener?.('change', update);
  }, []);

  useEffect(() => {
    if (isOpen) setMobileView('navigation');
  }, [isOpen]);

  const saveSettings = async (payload, success) => { setBusy(true); setStatus(''); try { const response = await fetch(`${API_URL}/api/social/settings`, { method: 'PUT', headers: getAuthHeaders(), body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Impossible de sauvegarder.'); onUpdateUser?.(data.user); setStatus(success); } catch (error) { setStatus(`Erreur : ${error.message}`); } finally { setBusy(false); } };
  const saveProfile = async (event) => { event.preventDefault(); const result = await onSaveProfile?.(profile); setStatus(result || 'Profil enregistré.'); };
  const savePassword = async (event) => { event.preventDefault(); if (password.newPassword !== password.confirmPassword) return setStatus('Erreur : les mots de passe ne correspondent pas.'); const result = await onChangePassword?.(password); setStatus(result || 'Mot de passe mis à jour.'); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); };
  const loadDevices = async () => { if (navigator.mediaDevices?.enumerateDevices) setDevices(await navigator.mediaDevices.enumerateDevices()); };
  const filteredGroups = useMemo(() => navGroups.map((group) => ({ ...group, items: group.items.filter(([, label]) => !search || `${group.title} ${label}`.toLowerCase().includes(search.toLowerCase())) })).filter((group) => group.items.length), [search]);
  const current = navGroups.flatMap((group) => group.items.map(([id, label]) => ({ id, label, group: group.title }))).find((item) => item.id === active) || { label: 'Paramètres', group: '' };
  const selectSetting = (id) => { setActive(id); onActiveChange?.(id); if (isMobile) setMobileView('content'); };
  const row = (label, description, control) => <div className="tavora-settings-row flex items-center justify-between gap-6 border-b border-white/[0.06] py-4"><div><p className="text-sm text-white/85">{label}</p><p className="mt-1 text-xs text-white/35">{description}</p></div>{control}</div>;
  const toggle = (value, setter, field) => <input type="checkbox" checked={Boolean(value[field])} onChange={(event) => setter((currentValue) => ({ ...currentValue, [field]: event.target.checked }))} className="h-4 w-4 accent-cyan-200" />;
  const activityToggle = (field) => <input type="checkbox" checked={Boolean(privacy.activity?.[field])} onChange={(event) => setPrivacy((current) => ({ ...current, activity: { ...current.activity, [field]: event.target.checked } }))} className="h-4 w-4 accent-cyan-200" />;
  const content = {
    account: <div className="space-y-5"><div className="flex items-center gap-4 border-b border-white/[0.07] pb-5"><Avatar user={user} /><div><h2 className="text-lg font-semibold">{user?.displayName || user?.username}</h2><p className="text-sm text-white/40">@{user?.username}</p></div></div>{row('Adresse e-mail', 'Adresse utilisée pour la connexion', <span className="text-sm text-white/55">{user?.email}</span>)}{row('Membre depuis', 'Date de création du compte', <span className="text-sm text-white/55">{user?.createdAt ? new Date(user.createdAt).toLocaleDateString('fr-FR') : 'Indisponible'}</span>)}</div>,
    profile: <form onSubmit={saveProfile} className="max-w-2xl space-y-4"><label className="block text-xs text-white/45">Nom d’affichage<input className={fieldClass} value={profile.displayName} onChange={(event) => setProfile({ ...profile, displayName: event.target.value })} /></label><label className="block text-xs text-white/45">Nom d’utilisateur<input className={fieldClass} value={profile.username} onChange={(event) => setProfile({ ...profile, username: event.target.value })} /></label><label className="block text-xs text-white/45">Bio<textarea className={`${fieldClass} resize-none`} rows={4} value={profile.bio} onChange={(event) => setProfile({ ...profile, bio: event.target.value })} /></label><button disabled={busy} className="flex items-center gap-2 rounded-md bg-cyan-200/10 px-4 py-2 text-sm text-cyan-100"><Save size={15} />Enregistrer</button></form>,
    security: <form onSubmit={savePassword} className="max-w-md space-y-3"><input required type="password" placeholder="Mot de passe actuel" className={fieldClass} value={password.currentPassword} onChange={(event) => setPassword({ ...password, currentPassword: event.target.value })} /><input required minLength={8} type="password" placeholder="Nouveau mot de passe" className={fieldClass} value={password.newPassword} onChange={(event) => setPassword({ ...password, newPassword: event.target.value })} /><input required minLength={8} type="password" placeholder="Confirmation" className={fieldClass} value={password.confirmPassword} onChange={(event) => setPassword({ ...password, confirmPassword: event.target.value })} /><button disabled={busy} className="rounded-md bg-cyan-200/10 px-4 py-2 text-sm text-cyan-100">Modifier le mot de passe</button></form>,
    privacy: <div>{row('Demandes d’amis', 'Qui peut vous envoyer une demande', <select className="rounded-md bg-[#0e0e13] p-2 text-sm text-cyan-100" value={privacy.friendRequests} onChange={(event) => setPrivacy({ ...privacy, friendRequests: event.target.value })}><option value="everyone">Tout le monde</option><option value="friendsOfFriends">Amis d’amis</option><option value="nobody">Personne</option></select>)}{row('Messages privés', 'Qui peut vous écrire', <select className="rounded-md bg-[#0e0e13] p-2 text-sm text-cyan-100" value={privacy.directMessages} onChange={(event) => setPrivacy({ ...privacy, directMessages: event.target.value })}><option value="everyone">Tout le monde</option><option value="friends">Amis</option><option value="nobody">Personne</option></select>)}<div className="mt-6 border-t border-white/[0.06] pt-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-cyan-200/60">Activité</p>{row('Afficher mon activité actuelle', 'Partager uniquement l’application détectée sur cet ordinateur', activityToggle('enabled'))}{row('Afficher les jeux auxquels je joue', 'Autoriser les activités de type jeu', activityToggle('games'))}{row('Afficher les applications compatibles', 'Autoriser les logiciels compatibles', activityToggle('applications'))}{row('Afficher le nom de l’application', 'Masquer le nom si nécessaire', activityToggle('showName'))}{row('Afficher depuis combien de temps', 'Afficher la durée de l’activité', activityToggle('showDuration'))}</div><button onClick={() => saveSettings({ privacy }, 'Confidentialité enregistrée.')} className="mt-5 rounded-md bg-cyan-200/10 px-4 py-2 text-sm text-cyan-100">Enregistrer</button></div>,
    notifications: <div>{row('Activer les notifications', 'Autoriser les notifications de messages privés', toggle(notifications, setNotifications, 'enabled'))}{row('Notifications de bureau', 'Afficher une notification native lorsque Tavora est en arrière-plan', toggle(notifications, setNotifications, 'desktop'))}{row('Aperçu du message', 'Afficher le contenu du message dans la notification', toggle(notifications, setNotifications, 'preview'))}{row('Photo de profil', 'Afficher l’avatar de l’expéditeur', toggle(notifications, setNotifications, 'avatar'))}{row('Messages privés', 'Nouveaux messages privés', toggle(notifications, setNotifications, 'directMessages'))}{row('Durée interne', 'Durée des notifications dans Tavora', <select value={notifications.duration} onChange={(event) => setNotifications({ ...notifications, duration: Number(event.target.value) })} className="rounded-md bg-[#0e0e13] p-2 text-sm text-cyan-100"><option value={3}>3 secondes</option><option value={5}>5 secondes</option><option value={10}>10 secondes</option></select>)}<button onClick={() => saveSettings({ notifications }, 'Notifications enregistrées.')} className="mt-5 rounded-md bg-cyan-200/10 px-4 py-2 text-sm text-cyan-100">Enregistrer</button></div>,
    appearance: <div>{row('Thème', 'Le thème sombre est actif dans Tavora', <span className="text-xs text-white/40">Sombre</span>)}{row('Réduire les animations', 'Limiter les transitions de l’interface', toggle(accessibility, setAccessibility, 'reduceMotion'))}</div>,
    accessibility: <div>{row('Taille du texte', 'Taille de lecture de l’application', <select className="rounded-md bg-[#0e0e13] p-2 text-sm text-cyan-100" value={accessibility.textSize} onChange={(event) => setAccessibility({ ...accessibility, textSize: event.target.value })}><option value="small">Petite</option><option value="normal">Normale</option><option value="large">Grande</option></select>)}{row('Contraste renforcé', 'Renforcer les contrastes de lecture', toggle(accessibility, setAccessibility, 'highContrast'))}<button onClick={() => saveSettings({ accessibility }, 'Accessibilité enregistrée.')} className="mt-5 rounded-md bg-cyan-200/10 px-4 py-2 text-sm text-cyan-100">Enregistrer</button></div>,
    voice: <div onFocus={loadDevices}>{row('Microphone', 'Périphérique utilisé à l’entrée vocale', <select className="max-w-52 rounded-md bg-[#0e0e13] p-2 text-xs text-cyan-100" value={voiceVideo.inputDeviceId} onChange={(event) => setVoiceVideo({ ...voiceVideo, inputDeviceId: event.target.value })}><option value="">Microphone par défaut</option>{devices.filter((device) => device.kind === 'audioinput').map((device) => <option key={device.deviceId} value={device.deviceId}>{device.label || 'Microphone'}</option>)}</select>)}{row('Suppression du bruit', 'Réduit les bruits du microphone', toggle(voiceVideo, setVoiceVideo, 'noiseSuppression'))}{row('Annulation d’écho', 'Évite le retour audio', toggle(voiceVideo, setVoiceVideo, 'echoCancellation'))}{row('Gain automatique', 'Ajuste le niveau du microphone', toggle(voiceVideo, setVoiceVideo, 'autoGainControl'))}{row('Caméra au démarrage', 'Demande la caméra en entrant en vocal', toggle(voiceVideo, setVoiceVideo, 'cameraEnabled'))}<button onClick={() => saveSettings({ voiceVideo }, 'Voix & Vidéo enregistrées.')} className="mt-5 flex items-center gap-2 rounded-md bg-cyan-200/10 px-4 py-2 text-sm text-cyan-100"><Volume2 size={15} />Enregistrer</button></div>,
    status: <div className="max-w-lg space-y-3"><label className="block text-xs text-white/45">Statut personnalisé<input className={fieldClass} value={status} onChange={(event) => setStatus(event.target.value)} /></label><button onClick={() => saveSettings({ customStatus: status }, 'Statut enregistré.')} className="rounded-md bg-cyan-200/10 px-4 py-2 text-sm text-cyan-100">Enregistrer</button></div>,
    servers: <div>{servers.map((server) => <div key={server.id} className="flex items-center gap-3 border-b border-white/[0.06] py-4"><span className="flex-1 text-sm text-white/75">{server.name}</span>{server.owner ? <button onClick={() => onOpenServerSettings(server)} className="text-xs text-cyan-100">Gérer</button> : <button onClick={() => onLeaveServer?.(server.id)} className="text-xs text-rose-200">Quitter</button>}</div>)}</div>,
    friends: <div className="space-y-3"><p className="text-sm text-white/60">{friends.length} ami(s), {incomingRequests.length} demande(s) reçue(s), {outgoingRequests.length} demande(s) envoyée(s).</p><button onClick={onOpenProfile} className="text-sm text-cyan-100">Ajouter un ami</button></div>,
    messages: <div>{row('Aperçu des liens', 'Afficher les aperçus dans les conversations', <span className="text-xs text-white/40">Activé</span>)}{row('Médias', 'Les téléchargements sont contrôlés par le navigateur', <span className="text-xs text-white/40">Navigateur</span>)}</div>,
    danger: <div className="border border-rose-300/20 p-4"><p className="text-sm text-white/80">Déconnexion</p><p className="mt-1 text-xs text-white/35">La session locale sera supprimée.</p><button onClick={onLogout} className="mt-4 rounded-md bg-rose-400/10 px-4 py-2 text-sm text-rose-200">Se déconnecter</button></div>,
  }[active];

  if (!isOpen) return null;
  if (isMobile && mobileView === 'navigation') return <MobileSettingsNavigation user={user} search={search} setSearch={setSearch} groups={filteredGroups} active={active} onSelect={selectSetting} onOpenProfile={onOpenProfile} onClose={onClose} />;
  if (isMobile) return <MobileSettingsContent current={current} content={content} onBack={() => setMobileView('navigation')} onClose={onClose} />;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-0 sm:p-4"><section className="flex h-full w-full max-w-6xl overflow-hidden bg-[#09090d] text-white shadow-2xl sm:h-[min(820px,94vh)] sm:rounded-xl"><aside className="w-72 shrink-0 overflow-y-auto border-r border-white/[0.06] bg-[#0d0d12] px-3 py-4 [scrollbar-width:thin] [scrollbar-color:#292932_transparent]"><div className="mb-5 flex items-center gap-3 rounded-lg px-3 py-2 transition hover:bg-white/[0.04]"><Avatar user={user} /><div className="min-w-0"><p className="truncate text-sm font-semibold">{user?.displayName || user?.username}</p><button type="button" onClick={onOpenProfile} className="text-xs text-white/40 hover:text-cyan-100">Modifier les profils</button></div></div><label className="mb-6 flex h-9 items-center gap-2 rounded-md border border-white/[0.06] bg-[#09090d] px-3 text-white/35 focus-within:border-cyan-200/30"><Search size={14} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher" className="min-w-0 flex-1 bg-transparent text-xs text-white outline-none placeholder:text-white/30" /></label>{filteredGroups.map((group) => <div key={group.title} className="mb-4"><p className="mb-1 px-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-white/25">{group.title}</p>{group.items.map(([id, label]) => <button type="button" key={id} onClick={() => setActive(id)} className={`flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-sm transition ${active === id ? 'bg-white/[0.09] text-white' : 'text-white/45 hover:bg-white/[0.04] hover:text-white'}`}><ChevronRight size={13} className={active === id ? 'text-cyan-200' : 'text-transparent'} />{label}</button>)}</div>)}</aside><main className="min-w-0 flex-1 overflow-y-auto bg-[#0b0b10] p-6 sm:p-10"><div className="mb-8 flex items-start justify-between border-b border-white/[0.07] pb-6"><div><p className="text-[10px] uppercase tracking-[0.2em] text-cyan-200/55">{current.group}</p><h1 className="mt-2 text-2xl font-semibold">{current.label}</h1><p className="mt-2 text-sm text-white/35">Gérez vos préférences Tavora.</p></div><button type="button" onClick={onClose} className="rounded-md p-2 text-white/35 transition hover:bg-white/[0.05] hover:text-white"><X size={18} /></button></div><div className="max-w-3xl">{content}{status ? <p className={`mt-6 text-sm ${status.startsWith('Erreur') ? 'text-rose-200' : 'text-cyan-100/80'}`}>{status}</p> : null}</div></main></section></div>;
}

function MobileSettingsNavigation({ user, search, setSearch, groups, active, onSelect, onOpenProfile, onClose }) {
  return <div className="tavora-mobile-settings-screen fixed inset-0 z-50 bg-[#09090d] text-white"><div className="h-full overflow-y-auto"><header className="border-b border-white/[0.07] px-5 pb-5 pt-6"><div className="flex items-center gap-3"><Avatar user={user} /><div className="min-w-0"><p className="truncate text-sm font-semibold">{user?.displayName || user?.username}</p><p className="truncate text-xs text-white/40">@{user?.username}</p><button type="button" onClick={onOpenProfile} className="mt-1 text-xs text-cyan-100/70">Modifier les profils</button></div><button type="button" onClick={onClose} aria-label="Fermer les paramètres" className="ml-auto rounded-lg p-2 text-white/40 hover:bg-white/10 hover:text-white"><X size={18} /></button></div><label className="mt-5 flex h-10 items-center gap-2 rounded-lg border border-white/[0.08] bg-[#101017] px-3 text-white/35"><Search size={15} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher dans les paramètres" className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/25" /></label></header><div className="space-y-6 px-4 py-6">{groups.map((group) => <section key={group.title}><p className="mb-2 px-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-white/30">{group.title}</p><div className="space-y-1">{group.items.map(([id, label]) => <button type="button" key={id} onClick={() => onSelect(id)} className={`flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-left text-sm transition ${active === id ? 'bg-white/[0.09] text-white' : 'text-white/55 hover:bg-white/[0.05] hover:text-white'}`}><ChevronRight size={14} className={active === id ? 'text-cyan-200' : 'text-transparent'} />{label}</button>)}</div></section>)}</div></div></div>;
}

function MobileSettingsContent({ current, content, onBack, onClose }) {
  return <div className="tavora-mobile-settings-screen fixed inset-0 z-50 bg-[#0b0b10] text-white"><header className="sticky top-0 z-10 flex h-14 items-center gap-2 border-b border-white/[0.07] bg-[#0b0b10]/95 px-4 backdrop-blur-xl"><button type="button" onClick={onBack} aria-label="Retour aux paramètres" className="rounded-lg p-2 text-white/55 hover:bg-white/10 hover:text-white"><ChevronRight size={18} className="rotate-180" /></button><div className="min-w-0 flex-1"><p className="text-[10px] uppercase tracking-[0.2em] text-cyan-200/55">{current.group}</p><h1 className="truncate text-sm font-semibold">{current.label}</h1></div><button type="button" onClick={onClose} aria-label="Fermer les paramètres" className="rounded-lg p-2 text-white/40 hover:bg-white/10 hover:text-white"><X size={18} /></button></header><main className="overflow-y-auto px-5 py-7"><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-cyan-200/60">{current.group}</p><h2 className="mt-2 text-2xl font-semibold">{current.label}</h2><p className="mt-2 max-w-md text-sm leading-6 text-white/45">Gérez vos préférences et les paramètres liés à votre compte Tavora.</p><div className="mt-8">{content}</div></main></div>;
}

function Avatar({ user }) {
  return (
    <div className="h-10 w-10 shrink-0 overflow-hidden rounded-full bg-white/[0.08] ring-1 ring-white/10">
      {user?.avatarUrl ? <img src={user.avatarUrl} alt="" className="h-full w-full object-cover" /> : <User className="m-2.5 text-white/40" />}
    </div>
  );
}
