import { useEffect, useRef, useState } from 'react';
import { acquireRealtimeSocket, releaseRealtimeSocket } from '../services/realtimeSocket';
import { AudioLines, ChevronLeft, ChevronRight, Clipboard, Download, Menu, Pause, Play, Search, Volume2, VolumeX, X } from 'lucide-react';
import MusicPlayer from './MusicPlayer';
import PlaylistEditor from './PlaylistEditor';
import PlaylistDetailOverlay from './PlaylistDetailOverlay';
import WindowControls from './WindowControls';

const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? 'http://localhost:5000' : 'https://backend-tavora.fly.dev');

const readableTitle = (file) => file.replace(/\.[^/.]+$/, '').replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').trim() || file;
const formatTime = (value) => {
  if (!Number.isFinite(value)) return '--:--';
  return `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, '0')}`;
};

function WhoisCard({ profile, onOpenProfile }) {
  const copy = async (value) => { if (value) await navigator.clipboard?.writeText(value); };
  const fields = [
    ['ID utilisateur', profile._id],
    ['Nom d’utilisateur', profile.username],
    ['Créé le', profile.createdAt ? new Date(profile.createdAt).toLocaleString('fr-FR') : null],
    ['Mis à jour le', profile.updatedAt ? new Date(profile.updatedAt).toLocaleString('fr-FR') : null],
  ].filter(([, value]) => value);

  return <article className="w-full max-w-xl overflow-hidden rounded-2xl border border-white/10 bg-[#111118] shadow-2xl">
    {profile.bannerUrl ? <img src={profile.bannerUrl} alt="" className="h-24 w-full object-cover" /> : <div className="h-16 bg-cyan-300/10" />}
    <div className="px-5 pb-5">
      <div className="-mt-8 flex items-end gap-3">
        {profile.avatarUrl ? <img src={profile.avatarUrl} alt={`Avatar de ${profile.username}`} className="h-16 w-16 rounded-2xl border-4 border-[#111118] object-cover" /> : <div className="flex h-16 w-16 items-center justify-center rounded-2xl border-4 border-[#111118] bg-cyan-300/15 text-xl font-semibold text-cyan-100">{profile.username?.[0]?.toUpperCase()}</div>}
        <div className="min-w-0 pb-1"><h3 className="truncate text-base font-semibold text-white">{profile.displayName || profile.username}</h3><p className="text-xs text-white/45">@{profile.username}</p></div>
      </div>
      {profile.bio ? <p className="mt-4 text-sm leading-6 text-white/65">{profile.bio}</p> : null}
      <div className="mt-5 border-t border-white/10 pt-4"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-cyan-200/65">Whois</p><dl className="mt-3 space-y-2">{fields.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-4 text-xs"><dt className="text-white/40">{label}</dt><dd className="max-w-[65%] break-all text-right text-white/75">{value}</dd></div>)}</dl></div>
      <div className="mt-5 flex flex-wrap justify-end gap-2"><button title="Copier l’identifiant" type="button" onClick={() => copy(profile._id)} className="rounded-lg border border-white/10 p-2 text-white/55 hover:bg-white/10 hover:text-white"><Clipboard size={15} /></button>{profile.avatarUrl ? <a title="Télécharger l’avatar" href={profile.avatarUrl} download={`avatar-${profile.username || 'utilisateur'}`} className="rounded-lg border border-white/10 p-2 text-white/55 hover:bg-white/10 hover:text-white"><Download size={15} /></a> : null}{profile.bannerUrl ? <a title="Télécharger la bannière" href={profile.bannerUrl} download={`banniere-${profile.username || 'utilisateur'}`} className="rounded-lg border border-white/10 p-2 text-white/55 hover:bg-white/10 hover:text-white"><Download size={15} /></a> : null}<button type="button" onClick={() => onOpenProfile(profile._id)} className="rounded-lg bg-cyan-200/10 px-3 py-2 text-xs font-semibold text-cyan-100 hover:bg-cyan-200/20">Ouvrir le profil</button></div>
    </div>
  </article>;
}

function SearchPanel({ getAuthHeaders, onClose, onOpenProfile }) {
  const [query, setQuery] = useState(''); const [users, setUsers] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => {
    const normalizedQuery = query.trim();
    if (normalizedQuery.length < 2) { setUsers([]); setLoading(false); setError(''); return undefined; }
    const controller = new AbortController();
    const timer = window.setTimeout(async () => {
      setLoading(true); setError(''); setSelected(null);
      try {
        const response = await fetch(`${API_URL}/api/social/users/search?q=${encodeURIComponent(normalizedQuery)}`, { headers: getAuthHeaders(), signal: controller.signal });
        const data = await response.json();
        if (!response.ok) throw new Error(data.message);
        setUsers(data.users || []);
      } catch (requestError) {
        if (requestError.name !== 'AbortError') { setUsers([]); setError(requestError.message || 'Recherche impossible.'); }
      } finally { if (!controller.signal.aborted) setLoading(false); }
    }, 300);
    return () => { controller.abort(); window.clearTimeout(timer); };
  }, [getAuthHeaders, query]);
  const submit = (event) => event.preventDefault();
  return <div className="absolute right-3 top-[calc(100%+10px)] z-50 w-[min(92vw,560px)] rounded-2xl border border-white/10 bg-[#0c0c12]/95 p-4 shadow-2xl backdrop-blur-xl"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Rechercher un utilisateur</h2><button title="Fermer" type="button" onClick={onClose} className="p-1 text-white/45 hover:text-white"><X size={16} /></button></div><form onSubmit={submit} className="flex gap-2"><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nom d’utilisateur" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white outline-none placeholder:text-white/30 focus:border-cyan-200/50" /><button title="Lancer la recherche" type="submit" className="rounded-lg bg-cyan-200/15 px-3 text-cyan-100 hover:bg-cyan-200/25"><Search size={16} /></button></form>{loading ? <p className="mt-4 text-xs text-white/45">Recherche en cours...</p> : error ? <p className="mt-4 text-xs text-rose-300">{error}</p> : selected ? <div className="mt-4"><WhoisCard profile={selected} onOpenProfile={onOpenProfile} /></div> : <div className="mt-4 space-y-1">{users.map((profile) => <button key={profile._id} type="button" onClick={() => setSelected(profile)} className="flex w-full items-center gap-3 rounded-xl p-2 text-left hover:bg-white/8">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" className="h-9 w-9 rounded-lg object-cover" /> : <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white/10 text-xs text-white">{profile.username?.[0]?.toUpperCase()}</div>}<span className="min-w-0"><strong className="block truncate text-sm text-white">{profile.displayName || profile.username}</strong><small className="text-xs text-white/40">@{profile.username}</small></span></button>)}{!users.length && query.length >= 2 ? <p className="text-xs text-white/35">Aucun utilisateur trouvé.</p> : null}</div>}</div>;
}

// eslint-disable-next-line no-unused-vars
function LegacyAudioPanel({ isOpen, onClose, onActivityChange }) {
  const audioRef = useRef(null); const shouldPlayRef = useRef(false); const [tracks, setTracks] = useState([]); const [index, setIndex] = useState(0); const [playing, setPlaying] = useState(false); const [progress, setProgress] = useState(0); const [duration, setDuration] = useState(0); const [volume, setVolume] = useState(0.8); const [freeMode, setFreeMode] = useState(false); const [position, setPosition] = useState({ x: 0, y: 12 }); const [size, setSize] = useState({ width: 520, height: 58 }); const interactionRef = useRef(null);
  useEffect(() => { fetch('/musiques/manifest.json').then((response) => response.json()).then((data) => setTracks((data.tracks || []).map((track) => typeof track === 'string' ? { file: track } : track))).catch(() => setTracks([])); }, []);
  const track = tracks[index];
  useEffect(() => { if (audioRef.current && track) { audioRef.current.src = `/musiques/${encodeURIComponent(track.file)}`; audioRef.current.load(); setProgress(0); setPlaying(false); if (shouldPlayRef.current) { audioRef.current.play().then(() => setPlaying(true)).catch(() => setPlaying(false)); } } }, [track]);
  useEffect(() => { onActivityChange?.({ currentTitle: track ? track.title || readableTitle(track.file) : null, isPlaying: playing, progress, duration, recentTracks: tracks.slice(0, 5).map((item) => item.title || readableTitle(item.file)) }); }, [duration, onActivityChange, playing, progress, track, tracks]);
  const toggle = async () => { if (!audioRef.current || !track) return; if (playing) { shouldPlayRef.current = false; audioRef.current.pause(); setPlaying(false); } else { shouldPlayRef.current = true; await audioRef.current.play(); setPlaying(true); } };
  const move = (step, autoPlay = false) => { shouldPlayRef.current = autoPlay; setIndex((current) => (current + step + tracks.length) % tracks.length); };
  const selectTrack = (nextIndex) => { shouldPlayRef.current = true; setIndex(nextIndex); };
  const startDrag = (event) => { if (!freeMode || event.target.closest('button, input')) return; event.currentTarget.setPointerCapture(event.pointerId); interactionRef.current = { type: 'drag', pointerX: event.clientX, pointerY: event.clientY, startX: position.x, startY: position.y }; };
  const updateDrag = (event) => { const interaction = interactionRef.current; if (!interaction) return; if (interaction.type === 'drag') setPosition({ x: interaction.startX + event.clientX - interaction.pointerX, y: Math.max(8, interaction.startY + event.clientY - interaction.pointerY) }); if (interaction.type === 'resize') setSize({ width: Math.min(720, Math.max(300, interaction.startWidth + event.clientX - interaction.pointerX)), height: interaction.startHeight }); };
  const stopInteraction = () => { interactionRef.current = null; };
  const startResize = (event) => { event.stopPropagation(); event.currentTarget.parentElement.setPointerCapture(event.pointerId); interactionRef.current = { type: 'resize', pointerX: event.clientX, startWidth: size.width, startHeight: size.height }; };
  const controls = track ? <><div className="mt-4 rounded-xl border border-white/8 bg-white/[0.04] p-3"><p className="truncate text-sm font-medium text-white">{track.title || readableTitle(track.file)}</p><p className="mt-1 text-[11px] text-cyan-200/55">{playing ? 'Lecture en cours' : 'Sélectionnée'}</p></div><div className="mt-3 max-h-32 space-y-1 overflow-y-auto">{tracks.map((item, itemIndex) => <button key={item.file} type="button" onClick={() => selectTrack(itemIndex)} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-xs transition ${itemIndex === index ? 'bg-cyan-200/10 text-cyan-100' : 'text-white/55 hover:bg-white/8 hover:text-white'}`}><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-white/8">{itemIndex === index && playing ? <AudioLines size={13} /> : <Play size={12} />}</span><span className="truncate">{item.title || readableTitle(item.file)}</span></button>)}</div><input aria-label="Progression" type="range" min="0" max={duration || 0} step="0.1" value={progress} onChange={(event) => { setProgress(Number(event.target.value)); if (audioRef.current) audioRef.current.currentTime = Number(event.target.value); }} className="mt-3 w-full accent-cyan-200" /><div className="flex justify-between text-[11px] text-white/40"><span>{formatTime(progress)}</span><span>{formatTime(duration)}</span></div><div className="mt-3 flex items-center justify-between"><button title="Piste précédente" type="button" disabled={tracks.length < 2} onClick={() => move(-1, playing)} className="p-2 text-white/55 disabled:opacity-30"><ChevronLeft size={17} /></button><button title={playing ? 'Pause' : 'Lecture'} type="button" onClick={toggle} className="rounded-full bg-cyan-200/15 p-3 text-cyan-100 hover:bg-cyan-200/25">{playing ? <Pause size={18} /> : <Play size={18} />}</button><button title="Piste suivante" type="button" disabled={tracks.length < 2} onClick={() => move(1, playing)} className="p-2 text-white/55 disabled:opacity-30"><ChevronRight size={17} /></button><label title="Volume" className="flex items-center gap-2 text-white/55">{volume ? <Volume2 size={16} /> : <VolumeX size={16} />}<input aria-label="Volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={(event) => { const next = Number(event.target.value); setVolume(next); if (audioRef.current) audioRef.current.volume = next; }} className="w-16 accent-cyan-200" /></label></div></> : <p className="mt-4 text-xs leading-5 text-white/40">Aucune musique disponible.</p>;
  return <><audio ref={audioRef} onTimeUpdate={() => setProgress(audioRef.current?.currentTime || 0)} onLoadedMetadata={() => setDuration(audioRef.current?.duration || 0)} onEnded={() => tracks.length && move(1, true)} />{isOpen ? <div className="absolute right-14 top-[calc(100%+10px)] z-50 w-[min(92vw,380px)] rounded-2xl border border-white/10 bg-[#0c0c12]/95 p-4 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Lecteur</h2><button title="Fermer le lecteur" type="button" onClick={onClose} className="p-1 text-white/45 hover:text-white"><X size={16} /></button></div>{controls}</div> : playing ? <div onContextMenu={(event) => { event.preventDefault(); setFreeMode((current) => !current); }} onPointerDown={startDrag} onPointerMove={updateDrag} onPointerUp={stopInteraction} className={`tavora-mini-player fixed z-[80] flex items-center gap-2.5 rounded-[22px] border border-white/[0.09] bg-[#111118]/95 px-2.5 py-2 shadow-[0_14px_36px_rgba(0,0,0,0.42)] backdrop-blur-2xl ${freeMode ? '' : 'left-1/2 top-3 -translate-x-1/2'}`} style={freeMode ? { left: `calc(50% + ${position.x}px)`, top: `${position.y}px`, width: `${size.width}px`, height: `${size.height}px` } : undefined} title={freeMode ? 'Mode libre actif : glisser pour déplacer, poignée pour redimensionner' : 'Clic droit pour activer le mode libre'}><div className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-[14px] bg-cyan-200/10 text-cyan-100"><AudioLines size={16} /></div>
<div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="truncate text-xs font-medium text-white/90">{track?.title || readableTitle(track?.file || '')}</span><span className="hidden shrink-0 text-[10px] tabular-nums text-white/35 sm:inline">{formatTime(progress)} / {formatTime(duration)}</span></div><input aria-label="Progression" type="range" min="0" max={duration || 0} step="0.1" value={progress} onChange={(event) => { setProgress(Number(event.target.value)); if (audioRef.current) audioRef.current.currentTime = Number(event.target.value); }} className="tavora-mini-progress mt-1 block h-1 w-full accent-cyan-200" /></div><div className="flex shrink-0 items-center gap-0.5"><button title="Piste precedente" type="button" onClick={() => move(-1, true)} className="rounded-full p-2 text-white/50 hover:bg-white/10 hover:text-white"><ChevronLeft size={15} /></button><button title="Pause" type="button" onClick={toggle} className="flex h-8 w-8 items-center justify-center rounded-full bg-cyan-200/15 text-cyan-100 hover:bg-cyan-200/25"><Pause size={15} /></button><button title="Piste suivante" type="button" onClick={() => move(1, true)} className="rounded-full p-2 text-white/50 hover:bg-white/10 hover:text-white"><ChevronRight size={15} /></button><button title="Rouvrir le lecteur" type="button" onClick={() => onClose(true)} className="hidden rounded-full p-2 text-white/40 hover:bg-white/10 hover:text-white sm:block"><AudioLines size={15} /></button><button title="Arreter la musique" type="button" onClick={() => { shouldPlayRef.current = false; audioRef.current?.pause(); setPlaying(false); }} className="rounded-full p-2 text-white/40 hover:bg-white/10 hover:text-white"><X size={15} /></button></div>{freeMode ? <button type="button" title="Redimensionner le lecteur" onPointerDown={startResize} className="tavora-mini-resize absolute bottom-1 right-1 h-3 w-3 cursor-se-resize rounded-sm bg-cyan-200/45" /> : null}</div> : null}</>;
}

export default function GlobalTopBar({ getAuthHeaders, onOpenProfile, userId, user, onToggleMobileSidebar }) {
  const [panel, setPanel] = useState(null); const [audioActivity, setAudioActivity] = useState(null); const [playlistEditorOpen, setPlaylistEditorOpen] = useState(false); const [selectedPlaylist, setSelectedPlaylist] = useState(null); const [musicTracks, setMusicTracks] = useState([]); const [publicPlaylists, setPublicPlaylists] = useState([]); const rootRef = useRef(null); const audioSocketRef = useRef(null);
  useEffect(() => { const close = (event) => { if (!rootRef.current?.contains(event.target)) setPanel(null); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { if (!userId) return undefined; const socket = acquireRealtimeSocket(); audioSocketRef.current = socket; return () => { socket.emit('audio:activity', { userId, isPlaying: false }); releaseRealtimeSocket(); audioSocketRef.current = null; }; }, [userId]);
  useEffect(() => { if (!userId || !audioSocketRef.current) return; audioSocketRef.current.emit('audio:activity', { userId, title: audioActivity?.currentTitle, isPlaying: Boolean(audioActivity?.isPlaying) }); }, [audioActivity, userId]);
  useEffect(() => {
    const openPlaylistEditor = (event) => {
      const createButton = event.target.closest('[title="Créer une playlist"]');
      if (createButton) { setPlaylistEditorOpen(true); Promise.all([fetch(`${API_URL}/api/music/tracks`), fetch(`${API_URL}/api/music/playlists`)]).then(async ([trackResponse, playlistResponse]) => { const trackData = await trackResponse.json(); const playlistData = await playlistResponse.json(); setMusicTracks(trackData.tracks || []); setPublicPlaylists(playlistData.playlists || []); }).catch(() => {}); return; }
      if (panel !== 'audio') return;
      const clickedButton = event.target.closest('button');
      const clickedTitle = clickedButton?.textContent?.trim();
      const clickedPlaylist = publicPlaylists.find((playlist) => clickedTitle?.startsWith(playlist.title));
      if (clickedPlaylist) window.dispatchEvent(new CustomEvent('tavora:open-playlist', { detail: clickedPlaylist }));
      else if (clickedTitle) fetch(`${API_URL}/api/music/playlists`).then((response) => response.json()).then((data) => { const match = (data.playlists || []).find((playlist) => clickedTitle.startsWith(playlist.title)); if (match) { setPublicPlaylists(data.playlists || []); window.dispatchEvent(new CustomEvent('tavora:open-playlist', { detail: match })); } }).catch(() => {});
    };
    const showPlaylist = (event) => setSelectedPlaylist(event.detail || null);
    document.addEventListener('click', openPlaylistEditor);
    window.addEventListener('tavora:open-playlist', showPlaylist);
    return () => { document.removeEventListener('click', openPlaylistEditor); window.removeEventListener('tavora:open-playlist', showPlaylist); };
  }, [panel, publicPlaylists]);
  const openProfile = (targetUserId) => { setPanel(null); onOpenProfile?.({ _id: targetUserId }); };
  return <><header ref={rootRef} className="relative z-40 flex h-11 shrink-0 items-center justify-between border-b border-white/[0.06] bg-[#08080b]/95 px-4 backdrop-blur-xl sm:px-5" style={{ WebkitAppRegion: 'drag' }}><div className="flex min-w-0 items-center gap-2"><button title="Ouvrir la navigation" type="button" onClick={onToggleMobileSidebar} className="tavora-topbar-menu rounded-md p-1.5 text-white/45 hover:bg-white/10 hover:text-white" style={{ WebkitAppRegion: 'no-drag' }}><Menu size={17} /></button><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-200/80" /><span className="truncate text-[13px] font-semibold tracking-[0.01em] text-white/90">Tavora</span></div><div className="flex shrink-0 items-center gap-0.5"><button title="Lecteur audio" type="button" onClick={() => { setPanel(panel === 'audio' ? null : 'audio'); setSelectedPlaylist(null); }} className="rounded-md p-1.5 text-white/45 hover:bg-white/10 hover:text-white" style={{ WebkitAppRegion: 'no-drag' }}><AudioLines size={16} /></button><button title="Rechercher un utilisateur" type="button" onClick={() => setPanel(panel === 'search' ? null : 'search')} className="rounded-md p-1.5 text-white/45 hover:bg-white/10 hover:text-white" style={{ WebkitAppRegion: 'no-drag' }}><Search size={16} /></button><MusicPlayer isOpen={panel === 'audio'} onClose={(reopen) => { setPanel(reopen ? 'audio' : null); setSelectedPlaylist(null); }} onActivityChange={setAudioActivity} getAuthHeaders={getAuthHeaders} user={user} />{panel === 'search' ? <SearchPanel getAuthHeaders={getAuthHeaders} onClose={() => setPanel(null)} onOpenProfile={openProfile} /> : null}</div><WindowControls /></header>{selectedPlaylist && panel === 'audio' ? <PlaylistDetailOverlay playlist={selectedPlaylist} tracks={musicTracks} onBack={() => setSelectedPlaylist(null)} /> : null}<PlaylistEditor open={playlistEditorOpen} tracks={musicTracks} getAuthHeaders={getAuthHeaders} onClose={() => { setPlaylistEditorOpen(false); setPanel(null); }} onSaved={() => { setPlaylistEditorOpen(false); setPanel(null); }} /></>;
}
