import { ArrowLeft, Copy, ListMusic, Play, Shuffle } from 'lucide-react';

export default function PlaylistDetailPanel({ playlist, tracks, onBack }) {
  if (!playlist) return null;
  const playlistTracks = (playlist.tracks || []).map((filename) => tracks.find((track) => track.filename === filename) || { filename });
  const play = (shuffle = false) => window.dispatchEvent(new CustomEvent('tavora:play-playlist', { detail: { ...playlist, shuffle } }));
  const share = async () => { await navigator.clipboard?.writeText(`${window.location.origin}/playlist/${playlist.id}`); };
  return <div className="fixed right-3 top-14 z-[60] w-[min(94vw,390px)] overflow-hidden rounded-2xl border border-white/10 bg-[#0c0c12]/98 shadow-2xl backdrop-blur-xl"><div className="h-24 bg-gradient-to-br from-cyan-300/30 via-fuchsia-300/20 to-transparent" style={playlist.banner ? { backgroundImage: `url(${playlist.banner})`, backgroundSize: 'cover', backgroundPosition: 'center' } : undefined} /><div className="-mt-7 px-4 pb-4"><div className="flex items-end gap-3"><div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-xl border-2 border-[#0c0c12] bg-cyan-200/15 text-cyan-100">{playlist.cover ? <img src={playlist.cover} alt="" className="h-full w-full object-cover" /> : <ListMusic size={22} />}</div><div className="min-w-0 pb-1"><h2 className="truncate text-base font-semibold text-white">{playlist.title}</h2><p className="truncate text-xs text-white/45">Par {playlist.ownerName || playlist.owner?.displayName || playlist.owner?.username || 'Utilisateur'} · {playlistTracks.length} titres</p></div></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-white/55">{playlist.description || 'Une sélection musicale publique.'}</p><div className="mt-3 flex gap-2"><button type="button" onClick={() => play(false)} className="rounded-full bg-cyan-200 px-3 py-2 text-xs font-semibold text-[#091016]"><Play size={13} className="mr-1 inline" />Lire</button><button type="button" onClick={() => play(true)} title="Lecture aléatoire" className="rounded-full border border-white/10 p-2 text-white/70 hover:bg-white/10"><Shuffle size={14} /></button><button type="button" onClick={share} title="Partager" className="rounded-full border border-white/10 p-2 text-white/70 hover:bg-white/10"><Copy size={14} /></button><button type="button" onClick={onBack} className="ml-auto rounded-full border border-white/10 p-2 text-white/50 hover:bg-white/10" title="Retour aux playlists"><ArrowLeft size={14} /></button></div><div className="mt-3 max-h-32 space-y-1 overflow-y-auto">{playlistTracks.map((track, index) => <button key={`${track.filename}-${index}`} type="button" onClick={() => window.dispatchEvent(new CustomEvent('tavora:play-track', { detail: track }))} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-xs text-white/65 hover:bg-white/8"><span className="w-4 text-white/30">{String(index + 1).padStart(2, '0')}</span><span className="truncate">{track.title || track.filename}</span><span className="ml-auto text-white/30">{track.artist || ''}</span></button>)}</div></div></div>;
}
