import { AlertTriangle, ArrowLeft, Check, Copy, ShieldAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? 'http://localhost:5000' : 'https://backend-tavora.fly.dev');
const reasonLabels = { harassment: 'Harcèlement', threats: 'Menaces', impersonation: 'Usurpation d’identité', spam: 'Spam', scam: 'Arnaque', dangerous: 'Contenu dangereux', hate: 'Discours haineux', abuse: 'Comportement abusif', other: 'Autre' };

export default function ModerationPage() {
  const { getAuthHeaders } = useAuth();
  const [reports, setReports] = useState([]);
  const [message, setMessage] = useState('');
  useEffect(() => { fetch(`${API_URL}/api/social/moderation/reports`, { headers: getAuthHeaders() }).then((response) => response.json()).then((data) => { if (data.reports) setReports(data.reports); else setMessage(data.message || 'Accès refusé.'); }).catch(() => setMessage('Impossible de charger les dossiers.')); }, [getAuthHeaders]);
  const warn = async (targetId) => { const response = await fetch(`${API_URL}/api/social/moderation/reports/${targetId}/warn`, { method: 'POST', headers: getAuthHeaders() }); const data = await response.json(); setMessage(data.message || (response.ok ? 'Avertissement envoyé.' : 'Action impossible.')); if (response.ok) setReports((items) => items.map((report) => report.targetId?._id === targetId ? { ...report, status: 'suspect', targetId: { ...report.targetId, isSuspect: true } } : report)); };
  const clear = async (targetId) => { const response = await fetch(`${API_URL}/api/social/moderation/users/${targetId}/suspect`, { method: 'DELETE', headers: getAuthHeaders() }); const data = await response.json(); setMessage(data.message || (response.ok ? 'Statut retiré.' : 'Action impossible.')); if (response.ok) setReports((items) => items.map((report) => report.targetId?._id === targetId ? { ...report, targetId: { ...report.targetId, isSuspect: false } } : report)); };
  const copyReviewLink = async (reportId) => { const response = await fetch(`${API_URL}/api/social/moderation/reports/${reportId}/review-link`, { method: 'POST', headers: getAuthHeaders() }); const data = await response.json(); if (response.ok) { await navigator.clipboard?.writeText(data.link); setMessage('Lien de revue sécurisé copié. Il expire dans 15 minutes.'); } else setMessage(data.message || 'Lien indisponible.'); };
  return <main className="min-h-screen bg-[#08080b] px-4 py-8 text-white sm:px-8"><div className="mx-auto max-w-5xl"><Link to="/home" className="inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={16} /> Accueil</Link><div className="mt-8 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-rose-200/70">Modération</p><h1 className="mt-2 text-3xl font-semibold">Dossiers de signalement</h1><p className="mt-2 text-sm text-white/45">Accès réservé aux comptes autorisés.</p></div><ShieldAlert className="text-rose-200/60" /></div>{message ? <p className="mt-5 rounded-lg border border-white/10 bg-white/[.04] p-3 text-sm text-cyan-100">{message}</p> : null}<div className="mt-8 space-y-3">{reports.map((report) => { const target = report.targetId; return <article key={report._id} className="rounded-xl border border-white/[.08] bg-white/[.03] p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">@{target?.username || 'utilisateur'}</p><p className="mt-1 text-xs text-white/40">Signalé le {new Date(report.createdAt).toLocaleString('fr-FR')} · {reasonLabels[report.reason] || report.reason}</p><p className="mt-2 text-sm text-white/60">{report.details || 'Aucun détail supplémentaire.'}</p></div><span className={`rounded-full px-2 py-1 text-[10px] uppercase tracking-[.14em] ${target?.isSuspect ? 'bg-rose-950 text-rose-200' : 'bg-white/[.06] text-white/50'}`}>{target?.isSuspect ? 'Compte suspect' : report.status}</span></div><div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={() => navigator.clipboard?.writeText(`${window.location.origin}/profile/${target?._id}`)} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60 hover:bg-white/10"><Copy size={14} /> Copier le lien de revue</button>{target?.isSuspect ? <button type="button" onClick={() => clear(target._id)} className="rounded-lg border border-emerald-300/15 px-3 py-2 text-xs text-emerald-200 hover:bg-emerald-300/10"><Check size={14} className="mr-1 inline" /> Retirer le statut</button> : <button type="button" onClick={() => warn(target?._id)} className="inline-flex items-center gap-2 rounded-lg bg-rose-400/15 px-3 py-2 text-xs font-semibold text-rose-100 hover:bg-rose-400/25"><AlertTriangle size={14} /> Envoyer l’avertissement</button>}</div></article>; })}{!reports.length && !message ? <p className="py-12 text-center text-sm text-white/40">Aucun dossier à traiter.</p> : null}</div></div></main>;
}
